name: ARM Template Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
    branches: [ main ]

jobs:
  validate-module-files-with-armttk:
    name: ARM TTK Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: microsoft/action-armttk/.github/workflows/arm-ttk@0.0.5
        with:
          workingPath: ./src